-- DISTINCT, LEFT_JOIN, LIKE
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND (Date('2022-10-01') < H.START_DATE AND  H.START_DATE < Date('2022-11-01'))
ORDER BY C.CAR_ID desc